grid_config:
  fps: 10
  attention:
    saliency_threshold: 0.35
  optical_flow:
    event_angles: [90, -90]
    angle_range_threshold: 20
    angle_diff_threshold: 75
    flow_threshold: 3
    nr_frames_moving_avg: 10
  grids:
    - top_left: [0.2, 0.45]
      bottom_right: [0.45, 0.7]
      rows: 1
      cols: 3
    - top_left: [0.55, 0.45]
      bottom_right: [0.8, 0.7]
      rows: 1
      cols: 3

detector_config:
  event_length_limit_seconds: [1, 10]
  cell_gap_time_limits:
    - [.1, 3]
    - [.1, 3]
    - [.5, 5]
    - [.1, 3]
    - [.1, 3]
  required_cell_subsets:
    - !!set { 1, 2, 3 }
    - !!set { 4, 5, 6 }
  detection_calibration_videos:
    - "000314"
  attention:
    cell_ranges:
      1: [3.0e-07, 5.0e-07]
      2: [7.0e-07, 9.0e-07]
      3: [1.5e-06, 1.8e-06]
      4: [3.18e-06, 3.4e-06]
      5: [6.4e-06, 6.75e-06]
      6: [1.3e-05, 1.35e-05]
  optical_flow:
    cell_ranges:
      1: [1.95e-05, 3.5e-05]
      2: [4.5e-05, 6.2e-05]
      3: [0.95e-04, 1.2e-04]
      4: [1.95e-04, 2.25e-04]
      5: [4.0e-04, 4.35e-04]
      6: [8.25e-04, 8.55e-04]
