# A pedestrian crosses the road
fps: 14
saliency_threshold: 0.2 # Saliency
grids:
  - top_left: [0.2, 0.45]
    bottom_right: [0.45, 0.7]
    rows: 1
    cols: 3
  - top_left: [0.55, 0.45]
    bottom_right: [0.8, 0.7]
    rows: 1
    cols: 3
required_cell_subsets:
  - !!set { 1, 2, 3 }
  - !!set { 4, 5, 6 }

attention:
  margin: 0
  cell_ranges: []
optical_flow:
  margin: 0
  cell_ranges: []
