# A vehicle performs a cut-in maneuver, cutting in from the left to the right
saliency_threshold: 0.4
angle_threshold: 114 # For running with OF
grids:
  - top_left: [0, 0.4]
    bottom_right: [0.6, 0.5]
    rows: 1
    cols: 6
    direction: "right"
