# A vehicle performs a cut-in maneuver, cutting in from the right to the left
saliency_threshold: 0.4
grids:
  - top_left: [0.4, 0.35]
    bottom_right: [1, 0.6]
    rows: 2
    cols: 6
    direction: "left"
