saliency_threshold: 0.4   # For running with attention
angle_threshold: 114      # For running with OF
grid_top_left:
  - 0
  - 0.35
grid_bottom_right:
  - 0.5
  - 0.6
grid_num_rows: 2
grid_num_cols: 6
grid_direction: right
