# A pedestrian crosses the road from the left to the right
direction: "right"
saliency_threshold: 0.2
angle_threshold: 90 # For running with Optical Flow
grids:
  - top_left: [0.2, 0.45]
    bottom_right: [0.45, 0.7]
    rows: 1
    cols: 3
  - top_left: [0.55, 0.45]
    bottom_right: [0.8, 0.7]
    rows: 1
    cols: 3
