grid_config:
  fps: 10
  attention:
    saliency_threshold: 0.2
  optical_flow:
    event_angles: [90, -90]
    angle_range_threshold: 20
    flow_threshold: 3
    angle_diff_threshold: 75
    nr_frames_moving_avg: 10
  grids:
    - top_left: [0.2, 0.45]
      bottom_right: [0.45, 0.7]
      rows: 1
      cols: 3
    - top_left: [0.55, 0.45]
      bottom_right: [0.8, 0.7]
      rows: 1
      cols: 3

detector_config:
  required_cell_subsets:
    - !!set { 1, 2, 3 }
    - !!set { 4, 5, 6 }
  detection_calibration_videos:
    - "1KIGitKyAbsQCXw66UGFU"
    - "00Jyiy3E2DstQTcaaRHsI"
    - "IFGmZTtK9U3ntir243GGt"
  attention:
    margin: 0
    cell_ranges:
      1: [4.0e-07, 4.2e-07]
      2: [8.0e-07, 8.4e-07]
      3: [1.55e-06, 1.7e-06]
      4: [3.18e-06, 3.4e-06]
      5: [6.45e-06, 6.7e-06]
      6: [1.25e-05, 1.4e-05]
  optical_flow:
    margin: 0
    cell_ranges:
      1: [2.62208e-05, 2.62208e-05]
      2: [5.24416e-05, 5.24416e-05]
      3: [0.0001048832, 0.0001572996]
      4: [0.000209716, 0.000629148]
      5: [0.0004195328, 0.0004195328]
      6: [0.0008390656, 0.0012585984]
