grid_config:
  fps: 10
  attention:
    saliency_threshold: 0.2
  optical_flow:
    event_angles: [90, -90]
    angle_range_threshold: 20
    flow_threshold: 3
    angle_diff_threshold: 75
    nr_frames_moving_avg: 10
  grids:
    - top_left: [0.2, 0.45]
      bottom_right: [0.45, 0.7]
      rows: 1
      cols: 3
    - top_left: [0.55, 0.45]
      bottom_right: [0.8, 0.7]
      rows: 1
      cols: 3

detector_config:
  event_length_limit_seconds: [1, 20]
  cell_gap_time_limits:
    - [0.1, 2]
    - [0.1, 2]
    - [0.3, 4]
    - [0.1, 2]
    - [0.1, 2]
  required_cell_subsets:
    - !!set { 1, 2, 3 }
    - !!set { 4, 5, 6 }
  detection_calibration_videos:
    - nep5WLDvfrGgEusiBrxPe
    - YGu13s0lKN3qBmtC3vc41
    - Lr1t1ufKrvbTruQUqtjaz
  attention:
    cell_ranges:
      1: [2.7e-07, 5.5e-07]
      2: [0.65e-06, 1.0e-06]
      3: [1.44e-06, 1.84e-06]
      4: [3.1e-06, 3.5e-06]
      5: [6.3e-06, 6.8e-06]
      6: [1.28e-05, 1.34e-05]
  optical_flow:
    cell_ranges:
      1: [1.8e-05, 3.5e-05]
      2: [4.7e-05, 6.0e-05]
      3: [0.95e-04, 1.2e-04]
      4: [1.95e-04, 2.25e-04]
      5: [4.05e-04, 4.35e-04]
      6: [8.2e-04, 8.5e-04]
